import * as fs from "fs";
import * as path from "path";

import { REWEQ } from "../REWEQ";
import { toFabfilterProQ1 } from "../REWToFabfilter";
import { toPlainObject } from "./helpers/testUtils";

// set this to true to debug the outputs as objects
const DO_DEBUG_OBJECT = false;

test("rew-Generic-6", () => {
  const filePath = path.join(
    __dirname,
    "data/genelec eq filters 6 Generic max boost.txt"
  );
  const fileContent = fs.readFileSync(filePath, "utf8");
  const filters = REWEQ.readREWEQFiltersFromString(fileContent, ",");
  const actual = filters && toFabfilterProQ1(filters);

  if (DO_DEBUG_OBJECT) console.log(JSON.stringify(actual, null, 2));
  expect(toPlainObject(actual)).toStrictEqual({
    Bands: [
      {
        ChannelMode: 0,
        Frequency: 63.5,
        Gain: -5.4,
        Q: 2.93,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 91.6,
        Gain: 14.2,
        Q: 2,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 136,
        Gain: -18.4,
        Q: 8.64,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 154,
        Gain: 16.6,
        Q: 14.31,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 170,
        Gain: -9.6,
        Q: 6.85,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 226,
        Gain: -5.8,
        Q: 15.94,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 249,
        Gain: -6.9,
        Q: 41.27,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 280,
        Gain: -8,
        Q: 30.08,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 389,
        Gain: -8.4,
        Q: 36.66,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 505,
        Gain: 12.2,
        Q: 39.39,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 654,
        Gain: -6.9,
        Q: 48.17,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 735,
        Gain: 10.6,
        Q: 39.01,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 770,
        Gain: -4.7,
        Q: 31.56,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 1067,
        Gain: -5.9,
        Q: 22.69,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 1275,
        Gain: -5.7,
        Q: 12.91,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 1889,
        Gain: 7.5,
        Q: 14.75,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 2129,
        Gain: -3.4,
        Q: 18.32,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 2829,
        Gain: -5.2,
        Q: 28.59,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 3221,
        Gain: -3,
        Q: 13.4,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 5126,
        Gain: -3.4,
        Q: 5.91,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: true,
      },
      {
        ChannelMode: 0,
        Frequency: 9.965784284662087,
        Gain: 0,
        Q: 0.5,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: false,
      },
      {
        ChannelMode: 0,
        Frequency: 9.965784284662087,
        Gain: 0,
        Q: 0.5,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: false,
      },
      {
        ChannelMode: 0,
        Frequency: 9.965784284662087,
        Gain: 0,
        Q: 0.5,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: false,
      },
      {
        ChannelMode: 0,
        Frequency: 9.965784284662087,
        Gain: 0,
        Q: 0.5,
        Shape: 0,
        LPHPSlope: 2,
        StereoPlacement: 2,
        Enabled: false,
      },
    ],
    Version: 2,
    ParameterCount: 190,
    OutputGain: 0,
    OutputPan: 0,
    DisplayRange: 2,
    ProcessMode: 0,
    ChannelMode: 0,
    Bypass: 0,
    ReceiveMidi: 0,
    Analyzer: 3,
    AnalyzerResolution: 1,
    AnalyzerSpeed: 2,
    SoloBand: -1,
  });
});
